// This is an autogenerated file. DO NOT change its contents manually.
'use server';
/**
 * @fileOverview Implements a Genkit flow to suggest local food and beverage pairings from the menu.
 *
 * - suggestPairings - A function that suggests food and beverage pairings.
 * - SuggestPairingsInput - The input type for the suggestPairings function.
 * - SuggestPairingsOutput - The return type for the suggestPairings function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPairingsInputSchema = z.object({
  foodItem: z.string().describe('The name of the food item for which to suggest a pairing.'),
});
export type SuggestPairingsInput = z.infer<typeof SuggestPairingsInputSchema>;

const SuggestPairingsOutputSchema = z.object({
  pairingSuggestion: z.string().describe('A suggestion for a food or beverage pairing that complements the input food item.'),
});
export type SuggestPairingsOutput = z.infer<typeof SuggestPairingsOutputSchema>;

export async function suggestPairings(input: SuggestPairingsInput): Promise<SuggestPairingsOutput> {
  return suggestPairingsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPairingsPrompt',
  input: {schema: SuggestPairingsInputSchema},
  output: {schema: SuggestPairingsOutputSchema},
  prompt: `You are a pairing expert at Cebo's KitchenStudio Hub, specializing in Zimbabwean and South African cuisine.

  Based on the food item provided, suggest a complementary item from our menu.

  Food Item: {{{foodItem}}}
  Menu: Starters, Main Course, Cocktails & Mocktails, Desserts. The cuisine features Zimbabwean and South African dishes.
  ZW tags are Zimbabwe and SA tags are South Africa
  Give pairing suggestion for this foodItem that is Zimbabwean or South African.
  Return the pairing suggestion.`,
});

const suggestPairingsFlow = ai.defineFlow(
  {
    name: 'suggestPairingsFlow',
    inputSchema: SuggestPairingsInputSchema,
    outputSchema: SuggestPairingsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
